# I Changed Properties to a yml file out of preference

# add debugging to run time logs
logging:
  level:
    org:
      #springframework: debug
# configuration for actuator for all services
management:
  endpoints:
    web:
      exposure:
        include: "*"
# spring configs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: test
    password: test123
  jpa:
    hibernate:
      ddl-auto: update #create (use to create tables)
  security:
    user:
      name: admin
      password: admin123




