# I Changed Properties to a yml file out of preference

# add debugging to run time logs
logging:
  level:
    org:
      springframework: debug
# configuration for actuator for all services
management:
  endpoints:
    web:
      exposure:
        include: "*"
# spring configs
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: BigDaddyData@96
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  security:
    user:
      name: admin
      password: admin123




